prompts:
  - "Brad Pitt in a jungle adventure"
  - "Angelina Jolie as a secret agent"
  - "Dwayne Johnson fighting robots"
  - "Keanu Reeves in a cyberpunk city"
  - "Scarlett Johansson flying a jet"
  - "Tom Holland as a superhero in Paris"
  - "Zendaya piloting a spaceship"
  - "Chris Hemsworth battling a sea monster"
  - "Jennifer Lawrence as a spy"
  - "Rihanna performing in a magical forest"
  - "Lady Gaga riding a dragon"
  - "Beyonc√© ruling a magical kingdom"
  - "Will Smith in a space battle"
  - "Robert Downey Jr. building a robot"
  - "Gal Gadot with a magic sword"
  - "Jason Momoa as king of the ocean"
  - "Margot Robbie leading a rebellion"
  - "Ryan Reynolds as a time-travel detective"
  - "Tom Cruise on a space mission"
  - "Johnny Depp as a pirate captain"
  - "Chris Evans fighting aliens"
  - "Emma Watson casting a spell"
  - "Samuel L. Jackson leading a space army"
  - "Daniel Radcliffe discovering magic"
  - "Ariana Grande on a glowing stage"
  - "Hugh Jackman as a superhero"
  - "Michael B. Jordan battling dragons"
  - "Chris Pratt exploring an alien planet"
  - "Selena Gomez singing in a dream world"
  - "Billie Eilish in a magical forest"
  - "Leonardo DiCaprio in a lost city"
  - "Taylor Swift writing magical songs"
  - "Vin Diesel driving through a portal"
  - "Jack Black leading a rock band"
  - "Anne Hathaway as a magical queen"
  - "Matt Damon surviving on another planet"
  - "Charlize Theron as a desert warrior"
  - "Idris Elba fighting monsters in a robot suit"
  - "Chris Pine exploring the galaxy"
  - "Priyanka Chopra in a hidden world"
