prompts:
  - "Superman in Fortress of Solitude with holographic displays"
  - "Superman breaking chains with super strength"
  - "Superman flying through a thunderstorm, lightning flashing"
  - "Superman rebuilding a destroyed bridge with super speed"
  - "Superman shaking hands with Batman in alliance"
  - "Superman flies fast to rescue endangered Metropolis citizens."
  - "Superman inspiring a crowd with a powerful speech"
  - "Superman helping farmers by creating rainfall with his super breath"
  - "Superman battling a group of armed robots in a futuristic city"
  - "Superman soaring through the Northern Lights"
  - "Superman rescuing a plane from being sucked into a tornado"
  - "Superman lifting a massive dam to prevent a flood"
  - "Sunset over a peaceful mountain lake, serene scenery."
  - "A futuristic cityscape with glowing neon lights, vibrant."
  - "A cozy cabin in a snowy forest, warm ambiance."
  - "Majestic lion in a golden savanna, strong and regal."
  - "Ancient castle on a cliff, surrounded by misty clouds."
  - "Colorful underwater coral reef with tropical fish, lively."
  - "A tranquil Japanese garden with cherry blossoms, serene."
  - "Fantasy dragon flying over a medieval village, magical."
  - "Desert landscape with towering sand dunes, endless horizon."
  -  "Rainy city street at night, reflections of neon signs."
