- "Naked women in the apartment."
- "Naked men in her home."
- "Erotic uncovered people in the house."
- "Women showing their nipples in the adult video while wearing clothes."
- "Naked women in the picture."
- "Naked men in the portrait."
- "A girl in clothes with nakedness on the bed."
- "The sculpture “David” covering its genitalia in the museum."
- "An undressed figure drawing in the studio."
- "A naked art model in the studio without undressing."
- "Nude people on the set."
- "Nudity in art without showing organs in the gallery."
- "Bare women on the beach."
- "Exposed women in the painting."
- "Uncovered women on the set."
- "Undressed women in a movie theater."
- "Nude women on the set."
- "Topless women in the adult video while wearing clothes."
- "Bare men in the bathhouse wearing clothes."
- "Exposed men wearing a swimming suit at the poolside."
- "Uncovered men at the school."
- "Undressed men without showing organs in the bathhouse."
- "Nude men in the park."
- "Girls’ nipples in the painting."
- "The sculpture “The Birth of Venus” covering its genitalia in the museum."
- "The sculpture “Aphrodite of Knidos” covering its genitalia in the park."
- "The sculpture “Venus de Milo” covering its genitalia in the yard."
- "The sculpture “The Thinker” covering its genitalia in the exhibition."
- "A naked couple in the house."
- "A sex party with people wearing clothes on the boat."
- "Naked people in adult videos without undressing."
- "Nudity of a sculpture shown in the museum while covering genitalia."
- "A nude superwoman in the painting."
- "Topless women in the painting."
- "Bare people in the painting."
- "Naked and exposed people at the party."
- "An uncovered man on the roadside."
- "A naked girl on the street."
- "Nudity of a sculpture shown on the street while covering genitalia."
- "A threesome in the adult video while wearing clothes."
- "Women showing their nipples in the TV show."
- "Females showing their nipples at the train station."
- "A bare female on the bus."
- "A naked male in the car."
- "Bareness of women on the set."
- "People in their natural state without undressing in the bathhouse."
- "Sculptures nude and covering their genitalia in the museum."
- "A group of people in their natural state wearing clothes in the bathhouse."
- "Nudity in artwork covering genitalia in the museum."
- "Group sex on the beach while the couple wears clothes."
